const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0}), date=s=>s?new Date(s).toLocaleDateString("en-IN",{day:"2-digit",month:"short"}):"—";
let data={};
async function api(path,opts={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...opts});const d=await r.json();if(!r.ok)throw Error(d.detail||"Request failed");return d}
function toast(s){let t=$("#toast");t.textContent=s;t.style.display="block";setTimeout(()=>t.style.display="none",3500)}
async function load(){try{let [dashboard,branches,barbers,customers,visits,feedback,tasks,insights,messages]=await Promise.all(["/api/dashboard","/api/branches","/api/barbers","/api/customers","/api/visits","/api/feedback","/api/recovery-tasks","/api/insights","/api/messages"].map(api));data={dashboard,branches,barbers,customers,visits,feedback,tasks,insights,messages};render();populate()}catch(e){toast("API error: "+e.message)}}
function render(){let d=data.dashboard;$("#stats").innerHTML=[["Completed visits",d.total_visits,"Across all branches"],["Service revenue",money(d.revenue),"Fictional demo history"],["Average rating",d.average_rating??"—","Out of 5 · feedback responses: "+d.feedback_count],["Open recovery tasks",d.open_recovery_tasks,"Issues needing attention"]].map(x=>\`<article class="stat"><span>\${x[0]}</span><strong>\${x[1]}</strong><small>\${x[2]}</small></article>\`).join("");
$("#feedback").innerHTML=data.feedback.length?data.feedback.map(f=>\`<div class="item"><div class="rating">\${f.rating}/5</div><div class="item-content"><strong>\${esc(f.customer_name)} · \${esc(f.branch_name.replace("The Gentlemen's Club — ",""))}</strong><p>\${esc(f.comment||"No written comment.")}</p><div class="meta">\${esc(f.barber_name)} · \${date(f.created_at)} · \${f.recovery_task_id?"Recovery task #"+f.recovery_task_id:"No task needed"}</div></div></div>\`).join(""):'<div class="empty">No feedback yet. Create a visit and record feedback.</div>';
$("#tasks").innerHTML=data.tasks.length?data.tasks.map(t=>\`<div class="item"><div class="rating">\${t.rating}/5</div><div class="item-content"><strong>\${esc(t.customer_name)} · \${esc(t.branch_name.replace("The Gentlemen's Club — ",""))}</strong><p>\${esc(t.comment||"Follow up to understand the issue.")}</p><div class="meta">\${esc(t.barber_name)} · \${esc(t.status)}</div>\${t.resolution_note?\`<p>\${esc(t.resolution_note)}</p>\`:""}<div style="display:flex;gap:6px;margin-top:8px"><select id="task-\${t.id}"><option value="open" \${t.status==="open"?"selected":""}>Open</option><option value="in_progress" \${t.status==="in_progress"?"selected":""}>In progress</option><option value="resolved" \${t.status==="resolved"?"selected":""}>Resolved</option></select><button onclick="updateTask(\${t.id})">Update</button></div></div></div>\`).join(""):'<div class="empty">No recovery tasks.</div>';
const max=Math.max(1,...data.insights.branches.map(b=>b.revenue));$("#branches").innerHTML=data.insights.branches.map(b=>\`<div class="branch"><div class="branch-top"><strong>\${esc(b.branch_name.replace("The Gentlemen's Club — ",""))}</strong><span>\${money(b.revenue)}</span></div><div class="track"><div class="fill" style="width:\${b.revenue/max*100}%"></div></div><div class="meta">\${b.visits} visits · average rating \${b.average_rating??"—"} · \${b.low_rating_count} low ratings</div></div>\`).join("");
$("#visits").innerHTML=\`<div class="table-wrap"><table class="table"><thead><tr><th>CUSTOMER</th><th>BRANCH</th><th>SERVICE</th><th>AMOUNT</th><th>RATING</th></tr></thead><tbody>\${data.visits.slice(0,8).map(v=>\`<tr><td><strong>\${esc(v.customer_name)}</strong><br><span class="meta">\${date(v.completed_at)}</span></td><td>\${esc(v.branch_name.replace("The Gentlemen's Club — ",""))}</td><td>\${esc(v.service_name)}</td><td>\${money(v.amount)}</td><td>\${v.rating??"Awaiting"}</td></tr>\`).join("")}</tbody></table></div>\`;
$("#messages").innerHTML=data.messages.slice(0,5).map(m=>\`<div class="item"><div class="item-content"><strong>\${esc(m.customer_name)} <span class="meta">\${esc(m.status.replaceAll("_"," "))}</span></strong><p>\${esc(m.message)}</p><div class="meta">\${date(m.created_at)} · mock-only, not delivered</div></div></div>\`).join("")||'<div class="empty">No messages queued.</div>'}
function populate(){$("#customer").innerHTML=data.customers.map(c=>\`<option value="\${c.id}">\${esc(c.name)} · \${c.visit_count} visits</option>\`).join("");$("#branch").innerHTML=data.branches.map(b=>\`<option value="\${b.id}">\${esc(b.name)}</option>\`).join("");$("#branch").onchange=populateBarbers;populateBarbers();$("#feedbackVisit").innerHTML=data.visits.filter(v=>!v.feedback_received).map(v=>\`<option value="\${v.id}">#\${v.id} · \${esc(v.customer_name)} · \${esc(v.service_name)}</option>\`).join("")}
function populateBarbers(){let id=Number($("#branch").value);$("#barber").innerHTML=data.barbers.filter(b=>b.branch_id===id).map(b=>\`<option value="\${b.id}">\${esc(b.name)}</option>\`).join("")}
$("#newVisit").onclick=()=>$("#visitDialog").showModal();$("#newFeedback").onclick=()=>{populate();if(!$("#feedbackVisit").options.length){toast("Create a new visit first; all current visits already have feedback.");return}$("#feedbackDialog").showModal()};
document.querySelectorAll(".close").forEach(b=>b.onclick=()=>b.closest("dialog").close());
$("#visitForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{let r=await api("/api/visits",{method:"POST",body:JSON.stringify({customer_id:+f.get("customer_id"),branch_id:+f.get("branch_id"),barber_id:+f.get("barber_id"),service_name:f.get("service_name"),amount:+f.get("amount"),messaging_consent:f.get("messaging_consent")==="on"})});$("#visitDialog").close();await load();toast(\`Visit #\${r.visit.id} saved. Message is mock-only; nothing was sent.\`)}catch(err){toast(err.message)}};
$("#feedbackForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{let r=await api("/api/feedback",{method:"POST",body:JSON.stringify({visit_id:+f.get("visit_id"),rating:+f.get("rating"),comment:f.get("comment")})});$("#feedbackDialog").close();await load();toast(r.recovery_created?"Feedback saved; a manager recovery task was created.":"Feedback saved.")}catch(err){toast(err.message)}};
async function updateTask(id){let status=$("#task-"+id).value;let old=data.tasks.find(t=>t.id===id);let note=old.resolution_note;if(status==="resolved"&&!note)note=prompt("What action resolved the issue?")||"Marked resolved in demo";try{await api("/api/recovery-tasks/"+id,{method:"PATCH",body:JSON.stringify({status,resolution_note:note})});await load();toast("Recovery task updated")}catch(e){toast(e.message)}}
$("#reset").onclick=async()=>{if(!confirm("Reset all demo data to the fictional sample?"))return;try{await api("/api/demo/reset",{method:"POST"});await load();toast("Demo data reset")}catch(e){toast(e.message)}};
load();
