"use client";
import Link from "next/link";
import {CalendarCheck2,CircleDollarSign,MessageCircle,Scissors,UsersRound,ArrowUpRight} from "lucide-react";
import {money} from "@/lib/api";
import {useWorkspace} from "@/components/WorkspaceProvider";
function StatCard({label,value,hint,icon:Icon}:{label:string;value:string;hint:string;icon:typeof CircleDollarSign}){return <article className="stat-card"><div className="stat-card-top"><span>{label}</span><span className="stat-icon"><Icon size={18}/></span></div><strong>{value}</strong><small>{hint}</small></article>}
export default function DashboardPage({role}:{role:"owner"|"barber"}){const {data}=useWorkspace();if(!data)return null;const d=data.dashboard;const owner=role==="owner";const branchMax=Math.max(1,...data.insights.branches.map(x=>x.revenue));const barberMax=Math.max(1,...data.insights.barbers.map(x=>x.revenue));
return <div className="page-stack"><section className="welcome-hero"><div><span className="eyebrow">{owner?"OWNER OVERVIEW":"YOUR WORKSPACE"}</span><h1>{owner?<>Your business,<br/><span>at a glance.</span></>:<>Every visit.<br/><span>Every detail.</span></>}</h1><p>{owner?"Understand branch performance, service revenue, and guest experience.":"Record customers and keep each visit accurate and traceable."}</p></div><Link href={owner?"/owner/visits?new=1":"/barber/visits?new=1"} className="button-primary"><Scissors size={17}/> Start recording</Link></section>
<section className="stats-grid"><StatCard label={owner?"Completed visits":"Your visits"} value={String(d.total_visits||0)} hint={owner?"Across all stores":"Assigned to your account"} icon={CalendarCheck2}/><StatCard label={owner?"Service revenue":"Your service total"} value={money(d.revenue)} hint="Recorded visit value" icon={CircleDollarSign}/><StatCard label="Average rating" value={d.average_rating==null?"—":Number(d.average_rating).toFixed(1)} hint={"From "+(d.feedback_count||0)+" feedback responses"} icon={MessageCircle}/><StatCard label={owner?"Open recovery tasks":"Repeat customers"} value={owner?String(d.open_recovery_tasks||0):String(d.repeat_customer_rate||0)+"%"} hint={owner?"Need follow-up":"Returned to your chair"} icon={UsersRound}/></section>
{owner?<div className="dashboard-columns"><section className="surface-card"><div className="section-heading-row"><div><h2>Branch performance</h2><p>Revenue and customer ratings by store.</p></div><Link href="/owner/finance" className="inline-link">Finance <ArrowUpRight size={15}/></Link></div><div className="bars-list">{data.insights.branches.map(b=><div className="bar-row" key={b.branch_name}><div className="bar-row-top"><strong>{b.branch_name.replace("The Gentlemen's Club — ","")}</strong><b>{money(b.revenue)}</b></div><div className="bar-track"><span style={{width:(b.revenue/branchMax*100)+"%"}}/></div><small>{b.visits} visits · Average rating {b.average_rating==null?"—":Number(b.average_rating).toFixed(1)}</small></div>)}{!data.insights.branches.length?<p className="empty-note">Branch statistics appear as visits are recorded.</p>:null}</div></section><section className="surface-card"><div className="section-heading-row"><div><h2>Employee performance</h2><p>Recorded service value by barber.</p></div></div><div className="bars-list">{data.insights.barbers.map(b=><div className="bar-row" key={b.barber_name}><div className="bar-row-top"><strong>{b.barber_name}</strong><b>{money(b.revenue)}</b></div><div className="bar-track"><span style={{width:(b.revenue/barberMax*100)+"%"}}/></div><small>{b.branch_name.replace("The Gentlemen's Club — ","")} · {b.visits} visits · {b.feedback_count} reviews</small></div>)}{!data.insights.barbers.length?<p className="empty-note">Employee statistics appear as visits are recorded.</p>:null}</div></section></div>
:<section className="surface-card"><div className="section-heading-row"><div><h2>Today's focus</h2><p>Keep check-ins accurate and review recent records.</p></div><Link href="/barber/visits" className="inline-link">Customer visits <ArrowUpRight size={15}/></Link></div><div className="quick-actions-grid"><Link href="/barber/visits?new=1" className="quick-action"><span className="quick-action-icon"><Scissors size={18}/></span><strong>Record a visit</strong><small>Add customer, services and total.</small></Link><Link href="/barber/customers" className="quick-action"><span className="quick-action-icon"><UsersRound size={18}/></span><strong>Your customers</strong><small>Review feedback from visits served.</small></Link><Link href="/barber/notifications" className="quick-action"><span className="quick-action-icon"><MessageCircle size={18}/></span><strong>Notifications</strong><small>Feedback on your visits.</small></Link></div></section>}</div>}
