"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowRight,Scissors,ShieldCheck} from "lucide-react";
import {api} from "@/lib/api";
import type {AuthResult,StaffUser} from "@/lib/types";
export default function LoginPage(){
 const router=useRouter();const [mode,setMode]=useState<"login"|"change">("login");const [identifier,setIdentifier]=useState("");const [password,setPassword]=useState("");const [currentPassword,setCurrentPassword]=useState("");const [nextPassword,setNextPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const enter=(user:StaffUser)=>router.replace(user.role==="owner"?"/owner":"/barber");
 useEffect(()=>{if(!sessionStorage.getItem("salonpulse_token"))return;api<StaffUser>("/api/auth/me").then((user)=>{if(user.must_change_password){setMode("change");setCurrentPassword("");}else enter(user);}).catch(()=>sessionStorage.removeItem("salonpulse_token"));},[]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const r=await api<AuthResult>("/api/auth/login",{method:"POST",body:JSON.stringify({identifier:identifier.trim(),password})});sessionStorage.setItem("salonpulse_token",r.access_token);if(r.user.must_change_password){setCurrentPassword(password);setMode("change");}else enter(r.user);}catch(x){setError(x instanceof Error?x.message:"Unable to sign in.");}finally{setBusy(false);}}
 async function change(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(nextPassword.length<12)return setError("Use at least 12 characters.");if(nextPassword!==confirm)return setError("The new passwords do not match.");setBusy(true);try{const r=await api<{user:StaffUser}>("/api/auth/change-password",{method:"POST",body:JSON.stringify({current_password:currentPassword,new_password:nextPassword})});enter(r.user);}catch(x){setError(x instanceof Error?x.message:"Unable to update password.");}finally{setBusy(false);}}
 function logout(){sessionStorage.removeItem("salonpulse_token");setMode("login");setPassword("");setCurrentPassword("");setNextPassword("");setConfirm("");setError("");}
 return <main className="login-background"><div className="login-layout"><section className="login-story"><div className="brand-lockup"><span className="brand-mark"><Scissors size={24}/></span><span className="brand-name">SalonPulse</span></div><span className="eyebrow story-eyebrow">SALON OPERATIONS PLATFORM</span><h1>Good service.<br/><span>Clearly recorded.</span></h1><p className="login-story-copy">Manage customer visits, preserve every correction, and understand how your salon is doing.</p><div className="login-proof"><ShieldCheck size={18}/>Separate owner and barber workspaces</div><div className="login-proof"><ShieldCheck size={18}/>Versioned customer visit records</div><div className="login-proof"><ShieldCheck size={18}/>Branch insights for owners</div></section>
 <section className="login-card"><div className="login-card-top"><span className="eyebrow">{mode==="login"?"WELCOME BACK":"ACCOUNT SECURITY"}</span><span className="login-card-mark"><Scissors size={21}/></span></div><h2>{mode==="login"?"Sign in to SalonPulse":"Choose a new password"}</h2><p className="text-muted">{mode==="login"?"Use your email or username to continue.":"Replace your temporary password before opening the workspace."}</p>
 {mode==="login"?<form onSubmit={login} className="form-stack"><label className="field-label">Email or username<input autoComplete="username" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="you@salonpulse.demo" required/></label><label className="field-label">Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/></label>{error?<p role="alert" className="alert-error">{error}</p>:null}<button className="button-primary w-full" type="submit" disabled={busy}>{busy?"Signing in…":"Sign in"}<ArrowRight size={17}/></button></form>
 :<form onSubmit={change} className="form-stack"><label className="field-label">Current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required/></label><label className="field-label">New password<input type="password" autoComplete="new-password" minLength={12} value={nextPassword} onChange={e=>setNextPassword(e.target.value)} required/></label><label className="field-label">Confirm new password<input type="password" autoComplete="new-password" minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error?<p role="alert" className="alert-error">{error}</p>:null}<button className="button-primary w-full" type="submit" disabled={busy}>{busy?"Saving…":"Save new password"}<ArrowRight size={17}/></button><button type="button" className="button-quiet w-full" onClick={logout}>Sign out instead</button></form>}
 <p className="login-footnote">Prototype · Fictional demo data · Messaging delivery is disabled</p></section></div></main>;
}
