-- Role-based login, immutable visit revision history, and visit-specific barber customer ratings.
create table if not exists public.staff_users (
  id integer generated by default as identity primary key,
  username varchar(80) not null unique,
  email varchar(255) not null unique,
  display_name varchar(120) not null,
  role varchar(20) not null check (role in ('owner', 'barber')),
  barber_id integer references public.barbers(id) on delete restrict,
  password_hash text not null,
  is_active boolean not null default true,
  must_change_password boolean not null default true,
  created_at timestamp without time zone not null default timezone('utc', now()),
  updated_at timestamp without time zone not null default timezone('utc', now()),
  constraint staff_role_barber_link check (
    (role = 'owner' and barber_id is null) or
    (role = 'barber' and barber_id is not null)
  )
);

create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  actor_user_id integer references public.staff_users(id) on delete set null,
  actor_username varchar(80) not null,
  actor_role varchar(20) not null,
  action varchar(40) not null,
  entity_type varchar(60) not null,
  entity_id integer not null,
  before_data jsonb,
  after_data jsonb,
  change_note varchar(500) not null default '',
  created_at timestamp without time zone not null default timezone('utc', now())
);

create index if not exists idx_audit_logs_entity_version
  on public.audit_logs(entity_type, entity_id, created_at desc);
create index if not exists idx_audit_logs_actor_time
  on public.audit_logs(actor_user_id, created_at desc);

create table if not exists public.customer_ratings (
  id integer generated by default as identity primary key,
  visit_id integer not null unique references public.visits(id) on delete cascade,
  customer_id integer not null references public.customers(id) on delete restrict,
  barber_user_id integer not null references public.staff_users(id) on delete restrict,
  rating integer not null check (rating between 1 and 5),
  note varchar(1000) not null default '',
  created_at timestamp without time zone not null default timezone('utc', now()),
  updated_at timestamp without time zone not null default timezone('utc', now())
);

alter table public.customers
  add column if not exists created_by_user_id integer references public.staff_users(id) on delete set null;

alter table public.visits
  add column if not exists created_by_user_id integer references public.staff_users(id) on delete set null;
alter table public.visits
  add column if not exists updated_by_user_id integer references public.staff_users(id) on delete set null;

-- Demo credentials: unique, random temporary passwords are delivered separately.
-- Every seeded account must change its password on first sign-in.
insert into public.staff_users
  (username, email, display_name, role, barber_id, password_hash, must_change_password)
values
  ('owner', 'owner@salonpulse.demo', 'SalonPulse Owner', 'owner', null,
   'pbkdf2_sha256$420000$rgc7iELvo2Hh0ct31Qr9cfG7$YoHf6h5XjLIguUMwtydvEbRQtcgRqt3HvXebYcKl2RE', true),
  ('aarav', 'aarav.patil@salonpulse.demo', 'Aarav Patil', 'barber', 1,
   'pbkdf2_sha256$420000$w7zWB5HuL6yCKqWbXu2yRgz8$-8vxoyUebQVitxwpzC8TQRqQ4OC3Wb_6-mXy8bTOo_o', true),
  ('rohan', 'rohan.jadhav@salonpulse.demo', 'Rohan Jadhav', 'barber', 2,
   'pbkdf2_sha256$420000$NKRdXyBel7zv7Ww_58_TS3Vx$n5mizeA-wYAOYGDVaHGZMrMH1XHm-OEwFWJtKXCatrU', true),
  ('kabir', 'kabir.shah@salonpulse.demo', 'Kabir Shah', 'barber', 3,
   'pbkdf2_sha256$420000$jbYrAb3Nwep9jJIqcFUFLiVV$7VO-yklqk_Dmlvao57KGYydVGCQZAc4frUer9R7bivM', true),
  ('dev', 'dev.kulkarni@salonpulse.demo', 'Dev Kulkarni', 'barber', 4,
   'pbkdf2_sha256$420000$rJ6-JDSluWWFx4EHUkK9tc8I$jNZecAvQETD_63p-yr3AfBCme1Yy_-K4eMOa_R_7aYo', true),
  ('ishaan', 'ishaan.more@salonpulse.demo', 'Ishaan More', 'barber', 5,
   'pbkdf2_sha256$420000$gCGjppxtE6oTzRJJiYnBRVmd$Pfkor6KFoFIcoWmrwFk6bNj8-HvglCQ4rIoNh4rvFNw', true),
  ('arjun', 'arjun.deshmukh@salonpulse.demo', 'Arjun Deshmukh', 'barber', 6,
   'pbkdf2_sha256$420000$VhPB6_LQmQFGtrNh9RSq7qsN$76dVSlme0o1BDB-K-N5QmiUzOdxhtqoTbhay6aCK4dc', true)
on conflict (username) do nothing;

alter table public.staff_users enable row level security;
alter table public.audit_logs enable row level security;
alter table public.customer_ratings enable row level security;
revoke all on table public.staff_users from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;
revoke all on table public.customer_ratings from anon, authenticated;
