-- SalonPulse core schema. Applied to the active Supabase development project.
create table if not exists public.branches (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  location varchar(120) not null
);
create table if not exists public.barbers (
  id integer generated by default as identity primary key,
  branch_id integer not null references public.branches(id) on delete restrict,
  name varchar(120) not null
);
create table if not exists public.customers (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  phone varchar(40) not null default '',
  messaging_consent boolean not null default false
);
create table if not exists public.visits (
  id integer generated by default as identity primary key,
  customer_id integer not null references public.customers(id) on delete restrict,
  branch_id integer not null references public.branches(id) on delete restrict,
  barber_id integer not null references public.barbers(id) on delete restrict,
  service_name varchar(120) not null,
  amount double precision not null check (amount >= 0),
  completed_at timestamp without time zone not null default timezone('utc', now()),
  feedback_requested boolean not null default false
);
create table if not exists public.feedback (
  id integer generated by default as identity primary key,
  visit_id integer not null unique references public.visits(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text not null default '',
  created_at timestamp without time zone not null default timezone('utc', now())
);
create table if not exists public.recovery_tasks (
  id integer generated by default as identity primary key,
  feedback_id integer not null references public.feedback(id) on delete cascade,
  status varchar(20) not null default 'open' check (status in ('open','in_progress','resolved')),
  resolution_note text not null default '',
  created_at timestamp without time zone not null default timezone('utc', now())
);
create table if not exists public.message_logs (
  id integer generated by default as identity primary key,
  visit_id integer not null references public.visits(id) on delete cascade,
  status varchar(40) not null default 'mock_queued',
  message text not null,
  created_at timestamp without time zone not null default timezone('utc', now())
);
