-- Customer contact details and normalized service lines for the visit workflow.
alter table public.customers
  add column if not exists location varchar(160) not null default '';

create table if not exists public.visit_services (
  id integer generated by default as identity primary key,
  visit_id integer not null references public.visits(id) on delete cascade,
  service_name varchar(120) not null,
  quantity integer not null default 1 check (quantity between 1 and 50),
  unit_price double precision not null check (unit_price >= 0),
  line_total double precision not null check (line_total >= 0)
);
create index if not exists idx_visit_services_visit_id
  on public.visit_services(visit_id);

-- Existing seeded contact details were masked placeholders, not callable numbers.
update public.customers
set phone = '',
    location = case name
      when 'Aditya Shah' then 'Viman Nagar'
      when 'Neel Joshi' then 'Kalyani Nagar'
      when 'Samir Desai' then 'Koregaon Park'
      when 'Riya Demo' then 'Kharadi'
      when 'Vikram Rao' then 'Wagholi'
      when 'Kunal Mehta' then 'Baner'
      else coalesce(location, '')
    end
where phone like '%*%';

-- Backfill one service line for visits created before multi-service support.
insert into public.visit_services (visit_id, service_name, quantity, unit_price, line_total)
select v.id, v.service_name, 1, v.amount, v.amount
from public.visits v
where not exists (
  select 1 from public.visit_services vs where vs.visit_id = v.id
);

-- Add another demo branch and barber for branch-specific selections.
insert into public.branches (name, location)
select 'The Gentlemen''s Club — Kalyani Nagar', 'Pune'
where not exists (
  select 1 from public.branches
  where name = 'The Gentlemen''s Club — Kalyani Nagar'
);

insert into public.barbers (branch_id, name)
select b.id, 'Arjun Deshmukh'
from public.branches b
where b.name = 'The Gentlemen''s Club — Kalyani Nagar'
  and not exists (
    select 1 from public.barbers br
    where br.name = 'Arjun Deshmukh' and br.branch_id = b.id
  );

alter table public.visit_services enable row level security;
revoke all on table public.visit_services from anon, authenticated;
