"use client";
import {useState} from "react";
import {MessageSquareText,X} from "@/components/icons";
import {api,dateTime,money} from "@/lib/api";
import {useWorkspace} from "@/components/WorkspaceProvider";
import type {Customer,Review} from "@/lib/types";
export default function CustomerDirectory(){
 const {data}=useWorkspace();const [selected,setSelected]=useState<Customer|null>(null);const [reviews,setReviews]=useState<Review[]|null>(null);const [visitCount,setVisitCount]=useState(0);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function openCustomer(c:Customer){setSelected(c);setReviews(null);setError("");setBusy(true);try{const result=await api<{customer:Customer;visit_count:number;review_count:number;reviews:Review[]}>("/api/customers/"+c.id+"/reviews");setReviews(result.reviews);setVisitCount(result.visit_count);}catch(e){setError(e instanceof Error?e.message:"Couldn't load feedback.");setReviews([]);}finally{setBusy(false);}}
 const customers=data?.customers||[];
 return <div className="page-stack"><section className="page-heading-block"><div><span className="eyebrow">CUSTOMER DIRECTORY</span><h1>Your customers</h1><p>Barbers see only customers they have served. Open a customer to review feedback linked to their visits.</p></div></section>
 {customers.length?<div className="customer-directory-grid">{customers.map(c=><button className="customer-directory-card" type="button" key={c.id} onClick={()=>openCustomer(c)}><span className="customer-avatar">{(c.name||"?").charAt(0).toUpperCase()}</span><span className="customer-directory-main"><strong>{c.name}</strong><small>{c.phone||"Phone not added"}</small><small>{c.location||"Area not added"}</small></span><span className="customer-directory-side"><b>{c.visit_count} {c.visit_count===1?"visit":"visits"}</b><small>{c.last_visit?"Last "+dateTime(c.last_visit):"See feedback"}</small></span></button>)}</div>:<section className="surface-card empty-state"><MessageSquareText size={24}/><strong>No customers yet</strong><p>Customers appear here after you record a visit.</p></section>}
 {selected?<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null);}}><section className="modal-card review-modal" role="dialog" aria-modal="true" aria-labelledby="reviewTitle"><div className="modal-heading"><div><span className="eyebrow">CUSTOMER PROFILE</span><h2 id="reviewTitle">{selected.name} · Feedback</h2><p>Reviews are tied to the visit where the customer submitted them.</p></div><button type="button" className="icon-button" onClick={()=>setSelected(null)} aria-label="Close"><X size={18}/></button></div><div className="review-stats"><div><strong>{visitCount}</strong><span>Visits served</span></div><div><strong>{reviews?.length??"—"}</strong><span>Reviews received</span></div></div>{error?<p className="alert-error">{error}</p>:null}{busy?<div className="loading-inline">Loading feedback…</div>:reviews?.length?<div className="review-list">{reviews.map(r=><article className="review-card" key={r.id}><div className="review-card-top"><span className="pill pill-accent">Visit {r.visit_number}</span><time>{dateTime(r.created_at||r.completed_at)}</time></div><div className="review-stars"><span>{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</span><b>{r.rating}/5</b></div><div className="review-service"><strong>{r.service_name}</strong><b>{money(r.amount)}</b></div>{r.comment?<p className="review-comment">{r.comment}</p>:<p className="small-muted">Star rating submitted without a written comment.</p>}<small className="small-muted">{dateTime(r.completed_at)} · {r.branch_name}</small></article>)}</div>:busy?null:<div className="empty-state"><MessageSquareText size={24}/><strong>No reviews yet</strong><p>This customer hasn't submitted feedback on your visits.</p></div>}<div className="modal-actions"><button className="button-secondary" type="button" onClick={()=>setSelected(null)}>Close</button></div></section></div>:null}
 </div>;
}
