"use client";
import {useEffect,useState} from "react";
import {ClipboardList,FileClock,Wallet} from "@/components/icons";
import {api,dateTime,money} from "@/lib/api";
import {useWorkspace} from "@/components/WorkspaceProvider";
import type {AuditLog,Feedback} from "@/lib/types";
export function FeedbackInbox(){
 const [rows,setRows]=useState<Feedback[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let active=true;api<Feedback[]>("/api/feedback?limit=100").then(r=>{if(active)setRows(r);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Couldn't load feedback.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 return <div className="page-stack"><section className="page-heading-block"><div><span className="eyebrow">CUSTOMER EXPERIENCE</span><h1>Feedback inbox</h1><p>Customer ratings and comments linked to their visit.</p></div></section><section className="surface-card">{error?<p role="alert" className="alert-error">{error}</p>:null}{loading?<div className="loading-inline">Loading feedback…</div>:rows.length?<div className="management-list">{rows.map(r=><article className="management-row" key={r.id}><div className="rating-number">{r.rating}/5</div><div className="management-row-main"><strong>{r.customer_name} · {r.branch_name.replace("The Gentlemen's Club — ","")}</strong><p>{r.comment||"No written comment."}</p><small>{r.barber_name} · {dateTime(r.created_at)} · {r.recovery_task_id?"Recovery task #"+r.recovery_task_id:"No recovery task"}</small></div></article>)}</div>:<div className="empty-state"><ClipboardList size={24}/><strong>No feedback yet</strong><p>Customer reviews will appear here when submitted.</p></div>}</section></div>;
}
export function AuditLogPage(){
 const [rows,setRows]=useState<AuditLog[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let active=true;api<AuditLog[]>("/api/audit-logs?limit=100").then(r=>{if(active)setRows(r);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Couldn't load audit log.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 return <div className="page-stack"><section className="page-heading-block"><div><span className="eyebrow">INTERNAL CONTROLS</span><h1>Audit log</h1><p>Management-only history of account actions and visit changes.</p></div></section><section className="surface-card">{error?<p role="alert" className="alert-error">{error}</p>:null}{loading?<div className="loading-inline">Loading audit history…</div>:rows.length?<div className="audit-list">{rows.map(r=><article className="audit-row" key={r.id}><span className="audit-icon"><FileClock size={17}/></span><div className="audit-row-main"><div className="audit-row-top"><strong>{r.actor_username} · {r.actor_role}</strong><time>{dateTime(r.created_at)}</time></div><p>{r.action.replaceAll("."," · ").replaceAll("_"," ")} · {r.entity_type} #{r.entity_id}</p>{r.change_note?<small>{r.change_note}</small>:null}<details><summary>Snapshot details</summary><pre>{JSON.stringify({before:r.before_data,after:r.after_data},null,2)}</pre></details></div></article>)}</div>:<div className="empty-state"><FileClock size={24}/><strong>No audit events</strong><p>New activity will appear here.</p></div>}</section></div>;
}
export function FinancePage(){const {data}=useWorkspace();if(!data)return null;const branches=data.insights.branches||[];const max=Math.max(1,...branches.map(b=>b.revenue));return <div className="page-stack"><section className="page-heading-block"><div><span className="eyebrow">BUSINESS PERFORMANCE</span><h1>Finance &amp; revenue</h1><p>Recorded service totals by store; this is visit value, not a full accounting ledger.</p></div></section><section className="stats-grid stats-grid-three"><article className="stat-card"><div className="stat-card-top"><span>Total recorded service value</span><span className="stat-icon"><Wallet size={18}/></span></div><strong>{money(data.dashboard.revenue)}</strong><small>Across recorded visits</small></article><article className="stat-card"><div className="stat-card-top"><span>Visits</span><span className="stat-icon"><ClipboardList size={18}/></span></div><strong>{data.dashboard.total_visits}</strong><small>Saved customer visits</small></article><article className="stat-card"><div className="stat-card-top"><span>Average ticket</span><span className="stat-icon"><Wallet size={18}/></span></div><strong>{money(data.dashboard.total_visits?data.dashboard.revenue/data.dashboard.total_visits:0)}</strong><small>Recorded value per visit</small></article></section><section className="surface-card"><div className="section-heading-row"><div><h2>Revenue by branch</h2><p>From saved customer visits.</p></div></div><div className="bars-list">{branches.map(b=><div className="bar-row" key={b.branch_name}><div className="bar-row-top"><strong>{b.branch_name.replace("The Gentlemen's Club — ","")}</strong><b>{money(b.revenue)}</b></div><div className="bar-track"><span style={{width:(b.revenue/max*100)+"%"}}/></div><small>{b.visits} visits recorded</small></div>)}{!branches.length?<p className="empty-note">Revenue data will appear as visits are recorded.</p>:null}</div></section></div>;}
