"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Plus,Trash2,X} from "@/components/icons";
import {api,fromLocalDateTimeInput,toLocalDateTimeInput} from "@/lib/api";
import type {Barber,Branch,Customer,ServiceCatalogItem,Visit} from "@/lib/types";
interface Line{service_name:string;quantity:number;unit_price:number;}
interface Props{visit?:Visit|null;branches:Branch[];barbers:Barber[];catalog:ServiceCatalogItem[];userBarberId?:number|null;onClose:()=>void;onSaved:()=>Promise<void>|void;}
export default function VisitEditor({visit,branches,barbers,catalog,userBarberId,onClose,onSaved}:Props){
const [mode,setMode]=useState<"new"|"returning">(visit?"returning":"new");const [name,setName]=useState(visit?.customer_name||"");const [phone,setPhone]=useState(visit?.customer_phone||"");const [location,setLocation]=useState(visit?.customer_location||"");const [customerId,setCustomerId]=useState<number|null>(visit?.customer_id||null);const [query,setQuery]=useState("");const [matches,setMatches]=useState<Customer[]>([]);const [branchId,setBranchId]=useState(visit?.branch_id||branches[0]?.id||0);const [barberId,setBarberId]=useState(visit?.barber_id||userBarberId||barbers[0]?.id||0);const [when,setWhen]=useState(toLocalDateTimeInput(visit?.completed_at));const [consent,setConsent]=useState(Boolean(visit?.feedback_requested));const [reason,setReason]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
const [lines,setLines]=useState<Line[]>(visit?.service_items?.length?visit.service_items.map(x=>({service_name:x.service_name,quantity:x.quantity,unit_price:x.unit_price})):[{service_name:visit?.service_name||catalog[0]?.name||"Haircut",quantity:1,unit_price:visit?.amount??catalog[0]?.default_price??300}]);
const total=useMemo(()=>lines.reduce((sum,x)=>sum+x.quantity*x.unit_price,0),[lines]);
useEffect(()=>{if(mode!=="returning"||query.trim().length<2||visit){setMatches([]);return;}let active=true;const timer=window.setTimeout(()=>{api<Customer[]>("/api/customers/search?q="+encodeURIComponent(query.trim())).then(r=>{if(active)setMatches(Array.isArray(r)?r:[]);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Customer search failed.");});},220);return()=>{active=false;window.clearTimeout(timer);};},[mode,query,visit]);
function updateLine(i:number,patch:Partial<Line>){setLines(rows=>rows.map((x,index)=>i===index?{...x,...patch}:x));}
function choose(i:number,value:string){const item=catalog.find(x=>x.name===value);updateLine(i,{service_name:value,unit_price:item?.default_price??lines[i].unit_price});}
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{
if(!lines.length||lines.some(x=>!x.service_name||x.quantity<1||x.unit_price<0))throw new Error("Add at least one valid service.");
if(mode==="returning"&&!customerId)throw new Error("Select a returning customer.");if(!visit&&mode==="new"&&(!name.trim()||!phone.trim()))throw new Error("Customer name and phone are required.");if(visit&&!reason.trim())throw new Error("Add a reason for this correction.");
const common={branch_id:Number(branchId),barber_id:Number(barberId),completed_at:fromLocalDateTimeInput(when),services:lines.map(x=>({service_name:x.service_name,quantity:Number(x.quantity),unit_price:Number(x.unit_price)}))};
let path="/api/visits",method="POST",payload:Record<string,unknown>;
if(visit){path+="/"+visit.id;method="PATCH";payload={...common,customer_id:customerId,messaging_consent:consent,change_note:reason.trim()};}
else payload=mode==="returning"?{...common,customer_id:customerId,messaging_consent:consent}:{...common,customer_name:name.trim(),customer_phone:phone.trim(),customer_location:location.trim(),messaging_consent:consent};
const result=await api<{visit:Visit;notice?:string}>(path,{method,body:JSON.stringify(payload)});await onSaved();onClose();window.dispatchEvent(new CustomEvent("salonpulse-toast",{detail:result.notice?"Visit saved. "+result.notice:visit?"Visit updated; prior version preserved.":"Customer visit recorded."}));
}catch(e){setError(e instanceof Error?e.message:"Could not save visit.");}finally{setBusy(false);}}
return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="modal-card visit-editor-modal" role="dialog" aria-modal="true" aria-labelledby="visitEditorTitle">
<div className="modal-heading"><div><span className="eyebrow">{visit?"VERSIONED CORRECTION":"CUSTOMER CHECK-IN"}</span><h2 id="visitEditorTitle">{visit?"Edit latest visit":"Start recording"}</h2><p>Every service and correction is saved with the visit.</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><X size={18}/></button></div>
<form className="form-stack" onSubmit={save}>
{!visit?<section className="form-section"><div className="section-heading-row"><div><h3>Customer</h3><p>Register a customer or choose one you have served.</p></div></div><div className="segmented-switch"><button type="button" className={mode==="new"?"selected":""} onClick={()=>{setMode("new");setCustomerId(null);}}>New customer</button><button type="button" className={mode==="returning"?"selected":""} onClick={()=>{setMode("returning");setCustomerId(null);}}>Returning</button></div>
{mode==="new"?<div className="form-grid-two"><label className="field-label">Customer name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label><label className="field-label">Phone number<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" autoComplete="tel" required/></label><label className="field-label form-span-two">Area (optional)<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Neighbourhood or area"/></label></div>
:<div className="form-stack compact-stack"><label className="field-label">Search customers you've served<input value={query} onChange={e=>{setQuery(e.target.value);setCustomerId(null);}} placeholder="Name or phone"/></label>{matches.length?<div className="search-match-list">{matches.map(c=><button className={customerId===c.id?"search-match selected":"search-match"} key={c.id} type="button" onClick={()=>{setCustomerId(c.id);setName(c.name);}}><strong>{c.name}</strong><span>{c.phone||"Phone not saved"} · {c.visit_count} visits</span></button>)}</div>:<p className="small-muted">Search by at least two characters to find a customer.</p>}{customerId?<p className="selected-inline">Selected customer: {name}</p>:null}</div>}</section>
:<div className="selected-customer-banner"><strong>{visit.customer_name}</strong><span>{visit.customer_phone||"Phone not added"} · Visit #{visit.id}</span><small>Customer assignment is locked for visit corrections.</small></div>}
<section className="form-section"><div className="section-heading-row"><div><h3>Visit details</h3><p>Record when the visit happened and who provided the service.</p></div></div><div className="form-grid-two"><label className="field-label">Branch<select value={branchId} onChange={e=>setBranchId(Number(e.target.value))} required>{branches.map(b=><option key={b.id} value={b.id}>{b.name.replace("The Gentlemen's Club — ","")}</option>)}</select></label><label className="field-label">Barber<select value={barberId} onChange={e=>setBarberId(Number(e.target.value))} required>{barbers.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><label className="field-label">Visit date &amp; time<input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} required/></label>{visit?<label className="field-label">Reason for correction (saved in history)<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} rows={2} placeholder="e.g. Corrected service price" required/></label>:null}</section>
<section className="form-section"><div className="section-heading-row"><div><h3>Services</h3><p>Quantities and prices determine the total.</p></div><span className="step-pill">{lines.length} line{lines.length===1?"":"s"}</span></div><div className="service-editor-list">{lines.map((line,i)=><div className="service-editor-row" key={i}><label className="field-label">Service<select value={line.service_name} onChange={e=>choose(i,e.target.value)}>{catalog.map(x=><option key={x.name} value={x.name}>{x.name}</option>)}</select></label><label className="field-label">Qty<input type="number" min={1} max={50} value={line.quantity} onChange={e=>updateLine(i,{quantity:Math.max(1,Number(e.target.value))})} required/></label><label className="field-label">Price (₹)<input type="number" min={0} max={100000} value={line.unit_price} onChange={e=>updateLine(i,{unit_price:Math.max(0,Number(e.target.value))})} required/></label><button type="button" className="remove-line-button" disabled={lines.length<=1} onClick={()=>setLines(rows=>rows.filter((_,index)=>index!==i))} aria-label="Remove service"><Trash2 size={17}/></button></div>)}</div><button type="button" className="button-add-line" disabled={lines.length>=10} onClick={()=>setLines(rows=>[...rows,{service_name:catalog[0]?.name||"Haircut",quantity:1,unit_price:catalog[0]?.default_price||300}])}><Plus size={16}/> Add another service</button><div className="form-total"><span>Total amount</span><strong>{total.toLocaleString("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2})}</strong></div></section>
{!visit?<label className="consent-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Customer agreed to receive feedback messages</span></label>:null}
{error?<p role="alert" className="alert-error">{error}</p>:null}<div className="modal-actions"><button type="button" className="button-secondary" onClick={onClose}>Cancel</button><button type="submit" className="button-primary" disabled={busy}>{busy?"Saving…":visit?"Save changes":"Complete check-in"}</button></div>
</form></section></div>;
}
